### ISSUE TITLE
while running train.sh

### ISSUE THREAD

**Issue by amiyamandal-dev** [kanekomasahiro/bert-gec#11]
```bash
| model transformer_s2_vaswani_wmt_en_de_big, criterion LabelSmoothedCrossEntropyCriterion
| num. model params: 354184960 (num. trained: 245874688)
| training on 1 GPUs
| max tokens per GPU = 4096 and max sentences per GPU = None
Model will load checkpoint from ../model/bert-base-cased/2222/checkpoint_last.pt
| loaded checkpoint ../model/bert-base-cased/2222/checkpoint_last.pt (epoch 10 @ 0 updates)
| loading train data for epoch 0
| ../process/bin train src-trg 34308 examples
| saved checkpoint ../model/bert-base-cased/2222/checkpoint0.pt (epoch 0 @ 0 updates) (writing took 24.50714635848999 seconds)
Traceback (most recent call last):
  File "../bert-nmt/train.py", line 315, in <module>
    cli_main()
  File "../bert-nmt/train.py", line 311, in cli_main
    main(args)
  File "../bert-nmt/train.py", line 89, in main
    train(args, trainer, task, epoch_itr)
  File "../bert-nmt/train.py", line 130, in train
    log_output = trainer.train_step(samples)
  File "/home/amiya/workspace/bert-gec/bert-nmt/fairseq/trainer.py", line 289, in train_step
    raise e
  File "/home/amiya/workspace/bert-gec/bert-nmt/fairseq/trainer.py", line 266, in train_step
    ignore_grad
  File "/home/amiya/workspace/bert-gec/bert-nmt/fairseq/tasks/fairseq_task.py", line 232, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/media/amiya/hdd/miniconda/envs/p37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/amiya/workspace/bert-gec/bert-nmt/fairseq/criterions/label_smoothed_cross_entropy.py", line 38, in forward
    net_output = model(**sample['net_input'])
  File "/media/amiya/hdd/miniconda/envs/p37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/amiya/workspace/bert-gec/bert-nmt/fairseq/models/transformer.py", line 339, in forward
    bert_encoder_out, _ =  self.bert_encoder(bert_input, output_all_encoded_layers=True, attention_mask= 1. - bert_encoder_padding_mask)
  File "/media/amiya/hdd/miniconda/envs/p37/lib/python3.7/site-packages/torch/tensor.py", line 396, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.
```

facing this issue when just running the bash script

**Comment by tranhamduong** [comment]
From: 
attention_mask= 1. - bert_encoder_padding_mask
Change it to: 
attention_mask= ~bert_encoder_padding_mask,
will work fine for me, this is a problem happened with pytorch version. 
You can fix it manually or try another pytorch version (1.0.0 or 1.1.0)

**Comment by amiyamandal-dev** [comment]
thanks @tranhamduong
