### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../bert-fuse/dict.src.txt'

### ISSUE THREAD

**Issue by Young1993** [kanekomasahiro/bert-gec#16]
When I run

./generate.sh ../test.txt 1

the error happens:

Generating...
Traceback (most recent call last):
  File "../bert-nmt/interactive.py", line 211, in <module>
    cli_main()
  File "../bert-nmt/interactive.py", line 207, in cli_main
    main(args)
  File "../bert-nmt/interactive.py", line 96, in main
    task = tasks.setup_task(args)
  File "/home/jy/xxx/bert-gec/bert-nmt/fairseq/tasks/__init__.py", line 19, in setup_task
    return TASK_REGISTRY[args.task].setup_task(args, **kwargs)
  File "/home/jy/xxx/bert-gec/bert-nmt/fairseq/tasks/translation.py", line 182, in setup_task
    src_dict = cls.load_dictionary(os.path.join(paths[0], 'dict.{}.txt'.format(args.source_lang)))
  File "/home/jy/xxx/bert-gec/bert-nmt/fairseq/tasks/fairseq_task.py", line 36, in load_dictionary
    return Dictionary.load(filename)
  File "/home/jy/xxx/bert-gec/bert-nmt/fairseq/data/dictionary.py", line 181, in load
    raise fnfe
  File "/home/jy/xxx/bert-gec/bert-nmt/fairseq/data/dictionary.py", line 175, in load
    with open(f, 'r', encoding='utf-8') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '../bert-fuse/dict.src.txt'

I'm wondering what is the `dict.src.txt` and where I can download the file? @kanekomasahiro , thank you

**Comment by Young1993** [comment]
The reason seems that I do not run the preprocess.py to produce the dict.src.txt'

**Comment by KaiPoChang** [comment]
I also encounter the same problem. Could you share the way how you solve this problem? Thank you!
