### ISSUE TITLE
dict.src.txt is missing from process/bin?

### ISSUE THREAD

**Issue by sabetAI** [kanekomasahiro/bert-gec#7]
I get the following traceback when running `train.sh`

```
Traceback (most recent call last):
  File "../bert-nmt/train.py", line 315, in <module>
    cli_main()
  File "../bert-nmt/train.py", line 311, in cli_main
    main(args)
  File "../bert-nmt/train.py", line 42, in main
    task = tasks.setup_task(args)
  File "/scratch/ssd001/home/asabet/bert-gec/bert-nmt/fairseq/tasks/__init__.py", line 19, in setup_task
    return TASK_REGISTRY[args.task].setup_task(args, **kwargs)
  File "/scratch/ssd001/home/asabet/bert-gec/bert-nmt/fairseq/tasks/translation.py", line 182, in setup_task
    src_dict = cls.load_dictionary(os.path.join(paths[0], 'dict.{}.txt'.format(args.source_lang)))
  File "/scratch/ssd001/home/asabet/bert-gec/bert-nmt/fairseq/tasks/fairseq_task.py", line 36, in load_dictionary
    return Dictionary.load(filename)
  File "/scratch/ssd001/home/asabet/bert-gec/bert-nmt/fairseq/data/dictionary.py", line 181, in load
    raise fnfe
  File "/scratch/ssd001/home/asabet/bert-gec/bert-nmt/fairseq/data/dictionary.py", line 175, in load
    with open(f, 'r', encoding='utf-8') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '../process/bin/dict.src.txt'
```

**Comment by kanekomasahiro** [comment]
https://github.com/kanekomasahiro/bert-gec/blob/master/scripts/train.sh#L42
`preprocess.py` here should create the `dict.src.txt` file. Does preprocess.py work correctly?

**Comment by sabetAI** [comment]
Script is working correctly, train/valid/test.src/trg were missing from the data directory. Thanks!
